FROM jboss/wildfly:10.1.0.Final

RUN /opt/jboss/wildfly/bin/add-user.sh "admin" "Admin#70365" --silent

RUN sed -i \
        -e 's|\(<https-listener\)|<ajp-listener name="ajp" socket-binding="ajp" scheme="http" enabled="true"/>\1|' \
        -e 's|^<subsystem xmlns="urn:jboss:domain:weld:3.0"/>|<subsystem xmlns="urn:jboss:domain:weld:3.0" require-bean-descriptor="true"/>|' \
        /opt/jboss/wildfly/standalone/configuration/standalone.xml

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]